use_gpu: True
federate:
  mode: 'standalone'
  total_round_num: 10
  make_global_eval: False
  client_num: 5
trainer:
  type: 'general'
eval:
  freq: 5
model:
  type: 'lr'
data:
  type: 'toy'
optimizer:
  lr: !contd '0.001,0.5'
  weight_decay: !disc [0.0, 0.0005, 0.005]
hpo:
  init_strategy: 'random'
