name: "API Rederence"
on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/"
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: doc/_build/html/
