name: "Pull Request Docs Check"
on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/"
