name: "API Reference"
on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  docs:
    if: false == contains(github.event.pull_request.title, 'WIP')
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/"
    - uses: actions/upload-artifact@v3
      with:
        name: DocumentationHTML
        path: doc/build/html/
